name:                tangora
version:             0.1.0.0
github:              "montmorency/tangora"
license:             BSD3
author:              "Henry Lambert"
maintainer:          "lamberh@tcd.ie"
copyright:           "2020 Henry Lambert"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/montmorency/tangora#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tangora-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tangora

tests:
  tangora-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tangora
